# This file defines a workflow that analyzes your codebase and intelligently creates a
# new configuration file with build/test/deploy jobs that are specific to your setup
version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  build-test-and-deploy:
    docker:
      - image: circleci/circleci-inferconfig:latest
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: yarn affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD

workflows:
  analyze-my-code:
    jobs:
      - build-test-and-deploy
