# This file defines a workflow that analyzes your codebase and intelligently creates a
# new configuration file with build/test/deploy jobs that are specific to your setup
version: 2.1
setup: true
orbs:
  node: circleci/node@1.1.6

jobs:
  build-test-and-deploy:
    docker:
      - image: cimg/node:20.4.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

workflows:
  analyze-my-code:
    jobs:
      - build-test-and-deploy
